name: gcal
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  google_fonts: ^6.1.0
  badges: ^3.1.2
  flutter_svg: ^2.0.9
  flutter_slidable: ^3.0.1
  flutter_spinkit: ^5.2.0
  sqflite: ^2.3.0
  supabase_flutter: ^2.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/first.svg
    - assets/images/second.svg
    - assets/images/third.svg
    - assets/images/splash.png
    - assets/images/landing-back.jpg
    - assets/images/landing1.svg
    - assets/images/landing2.svg
    - assets/images/input/email.png
    - assets/images/input/phone.png
    - assets/images/input/google.png
    - assets/images/home/plate.png
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
